#!/usr/bin/env php
<?php

declare(strict_types=1);

require __DIR__ . '/vendor/autoload.php';

use app\Container;
use app\console\ConsoleApplication;

error_reporting(E_ALL);
ini_set('display_errors', '1');

$container = new Container();
$application = new ConsoleApplication($container);
exit($application->run($argv));
